# Generated by Django 5.0.14 on 2025-08-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspot',
            name='image_url',
            field=models.CharField(default='spotimages/pikachu.jpg', max_length=100),
        ),
    ]
