# Generated by Django 5.0.14 on 2025-08-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studyspot_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyspot',
            name='image_url',
            field=models.CharField(default='pikachu.jpg', max_length=100),
        ),
    ]
