# Generated by Django 5.0.14 on 2025-08-20 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_studyspot_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyspot',
            name='image_url',
        ),
        migrations.CreateModel(
            name='SpotImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('studySpot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.studyspot')),
            ],
        ),
    ]
