# Generated by Django 5.0.14 on 2025-08-21 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_studyspot_image_url_spotimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusynessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionDate', models.DateTimeField(auto_now_add=True)),
                ('studySpot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studyspot')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.score')),
            ],
        ),
    ]
