# Generated by Django 5.0.14 on 2025-08-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_score_busynesslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
